### ISSUE TITLE
4.3.1 throws error on forge 30.051

### ISSUE THREAD

**Issue by Seegras** [Szewek/Flux#3] opened 2020-01-26 12:44 UTC
```
Flux (flux) has failed to load correctly
net/minecraftforge/fml/config/Modconfig$ConfigReloading
```
This is with flux as sole mod apart from forge itself.

**Comment by Szewek** [comment] 2020-01-26 13:04
Duplicate of #2. The fix is applied in 4.3.2.

**Closed by Szewek** 2020-01-26 13:04 UTC
